// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ssl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSsl returns the embedded CollectionSpec for ssl.
func loadSsl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ssl: %w", err)
	}

	return spec, err
}

// loadSslObjects loads ssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sslObjects
//	*sslPrograms
//	*sslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSsl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslSpecs struct {
	sslProgramSpecs
	sslMapSpecs
	sslVariableSpecs
}

// sslProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslProgramSpecs struct {
	UprobeGoTlsReadEntry *ebpf.ProgramSpec `ebpf:"uprobe_go_tls_read_entry"`
	UprobeGoTlsWrite     *ebpf.ProgramSpec `ebpf:"uprobe_go_tls_write"`
	UprobePrReadEntry    *ebpf.ProgramSpec `ebpf:"uprobe_pr_read_entry"`
	UprobePrWrite        *ebpf.ProgramSpec `ebpf:"uprobe_pr_write"`
	UprobeSslReadEntry   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslWrite       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeGoTlsRead   *ebpf.ProgramSpec `ebpf:"uretprobe_go_tls_read"`
	UretprobePrRead      *ebpf.ProgramSpec `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead     *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
}

// sslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslMapSpecs struct {
	SslBufPtrs *ebpf.MapSpec `ebpf:"ssl_buf_ptrs"`
	SslEvents  *ebpf.MapSpec `ebpf:"ssl_events"`
}

// sslVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslVariableSpecs struct {
}

// sslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslObjects struct {
	sslPrograms
	sslMaps
	sslVariables
}

func (o *sslObjects) Close() error {
	return _SslClose(
		&o.sslPrograms,
		&o.sslMaps,
	)
}

// sslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslMaps struct {
	SslBufPtrs *ebpf.Map `ebpf:"ssl_buf_ptrs"`
	SslEvents  *ebpf.Map `ebpf:"ssl_events"`
}

func (m *sslMaps) Close() error {
	return _SslClose(
		m.SslBufPtrs,
		m.SslEvents,
	)
}

// sslVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslVariables struct {
}

// sslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslPrograms struct {
	UprobeGoTlsReadEntry *ebpf.Program `ebpf:"uprobe_go_tls_read_entry"`
	UprobeGoTlsWrite     *ebpf.Program `ebpf:"uprobe_go_tls_write"`
	UprobePrReadEntry    *ebpf.Program `ebpf:"uprobe_pr_read_entry"`
	UprobePrWrite        *ebpf.Program `ebpf:"uprobe_pr_write"`
	UprobeSslReadEntry   *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslWrite       *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeGoTlsRead   *ebpf.Program `ebpf:"uretprobe_go_tls_read"`
	UretprobePrRead      *ebpf.Program `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead     *ebpf.Program `ebpf:"uretprobe_ssl_read"`
}

func (p *sslPrograms) Close() error {
	return _SslClose(
		p.UprobeGoTlsReadEntry,
		p.UprobeGoTlsWrite,
		p.UprobePrReadEntry,
		p.UprobePrWrite,
		p.UprobeSslReadEntry,
		p.UprobeSslWrite,
		p.UretprobeGoTlsRead,
		p.UretprobePrRead,
		p.UretprobeSslRead,
	)
}

func _SslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssl_x86_bpfel.o
var _SslBytes []byte
